Remove npm-check dependency
xlts-dev/angularjs-angular-hybrid-angular-cli pull request #14
Opened 2023-05-21 14:28 UTC by jzolnowski

Fix the [Got allows a redirect to a UNIX socket](https://github.com/xlts-dev/angularjs-angular-hybrid-angular-cli/security/dependabot/60) security issue

2023-05-22 16:48 UTC, gkalpak requested changes

2023-05-22 16:48 UTC, gkalpak commented on package-lock.json
We shouldn't be changing to lockfile version in this PR.

2023-05-25 10:17 UTC, jzolnowski commented
I updated the commit message, generated package-json without changing `lockfileVersion`, replaced `npm-check` with [npm-check-updates](https://github.com/raineorshine/npm-check-updates). At this point, it doesn't have any [vulnerabilities](https://security.snyk.io/package/npm/npm-check-updates)

2023-05-26 15:37 UTC, gkalpak approved these changes
The changes lgtm :+1:

2023-05-26 15:51 UTC, merged