chore(package.json): bump angular.js to v1.9.2
xlts-dev/angularjs-angular-hybrid-angular-cli pull request #24
Opened 2023-08-07 06:55 UTC by jzolnowski

2023-08-07 10:19 UTC, gkalpak requested changes
We should also update the lockfile.

2023-08-07 10:19 UTC, gkalpak commented on package.json
>      "angular": "npm:@xlts.dev/angular@1.9.1",
This also needs updating.

2023-08-10 15:04 UTC, jzolnowski commented on package.json
>      "angular": "npm:@xlts.dev/angular@1.9.1",
Done. Lock file updated as well

2023-08-11 08:08 UTC, gkalpak requested changes
This PR now contains more updates than just _"angular.js to v1.9.2"_.
We should either limit the changes to AngularJS or update the commit message to reflect the actual changes.

2023-08-11 13:15 UTC, jzolnowski commented
Commit message updated

2023-08-11 15:51 UTC, gkalpak commented
What do you mean by _"angular.js-based libraries"_?

2023-08-14 12:59 UTC, jzolnowski commented
> What do you mean by _"angular.js-based libraries"_?

All the rest angular.js based packages like:
```
 "angular-animate": "npm:@xlts.dev/angular-animate@^1.9.2",
 "angular-aria": "npm:@xlts.dev/angular-aria@^1.9.2",
 "angular-material": "npm:@xlts.dev/angular-material@^1.2.4",
 "angular-messages": "npm:@xlts.dev/angular-messages@^1.9.2",
 "angular-sanitize": "npm:@xlts.dev/angular-sanitize@^1.9.2",
 ```

2023-08-14 13:47 UTC, gkalpak requested changes
>> What do you mean by _"angular.js-based libraries"_?
>
> All the rest angular.js based packages like:
> ```
>  "angular-animate": "npm:@xlts.dev/angular-animate@^1.9.2",
>  "angular-aria": "npm:@xlts.dev/angular-aria@^1.9.2",
>  "angular-material": "npm:@xlts.dev/angular-material@^1.2.4",
>  "angular-messages": "npm:@xlts.dev/angular-messages@^1.9.2",
>  "angular-sanitize": "npm:@xlts.dev/angular-sanitize@^1.9.2",
>  ```

I see. I don't think we need to explicitly mention these libraries in the commit message, since they are part of the AngularJS framework and can be collectively referred to as AngularJS. 

But this PR also updates other non-AngularJS related dependencies. We should either mention that in the commit message or move those other updates to a separate commit/PR.

2023-08-15 19:00 UTC, jzolnowski commented
> But this PR also updates other non-AngularJS related dependencies. We should either mention that in the commit message to move those other updates to a separate commit/PR.

It's mentioned by `Also update lockfile.` commit part 😄

2023-08-16 09:36 UTC, gkalpak commented
>> But this PR also updates other non-AngularJS related dependencies. We should either mention that in the commit message to move those other updates to a separate commit/PR.
>
> It's mentioned by `Also update lockfile.` commit part 😄

Not sure if this is supposed to be a serious answer or a joke (given the 😄 at the end) 😅, but (just in case):
a. _"update lockfile"_ does not really give any info on what/why/how it was updated and does not necessarily imply that dependencies were upgraded and
b. there is not reason to not mention this in the commit message header and bury it in the body.

2023-08-16 20:53 UTC, gkalpak approved these changes
Awesome 😍
Thank you!

2023-08-16 20:53 UTC, merged